### ISSUE TITLE
Barista hanging on compilation

### ISSUE THREAD

**Issue by d2kagw** [Sutto/barista#1]
I've been using Barista for a few months now, but just recently it's started to hang when run through the Rails 3 development server.

When I run:

```
rails server
```

and hit the URL, the page starts loading and just hangs there.
If I exit `rails server` I get the following stack trace (note the `Completed` time is how long I waited before killing the server)

```
Started GET "/" for 127.0.0.1 at Mon Aug 23 13:36:09 +1000 2010
  Processing by IndexController#index as HTML
[Barista] Compiling all scripts
[Barista] Compiling all coffeescripts
[Barista] Compiling quince/Controllers.coffee from framework 'default'
Completed   in 32910ms

Barista::CompilationError ("coffee -p '<long file path>/app/coffeescripts/quince/Controllers.coffee'" exited with a non-zero status.):
/Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista/compiler.rb:72:in `invoke_coffee'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista/compiler.rb:34:in `compile!'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista/compiler.rb:39:in `to_js'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista/compiler.rb:23:in `compile'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista.rb:88:in `compile_file!'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista.rb:105:in `compile_all!'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista.rb:104:in `each'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista.rb:104:in `compile_all!'
  /Users/wallisa/.bundle/ruby/1.8/gems/barista-0.5.0/lib/barista/filter.rb:6:in `filter'
  ....
```

Any ideas?

**Comment by Sutto** [comment]
What does manually running:

```
coffee -p '/Users/wallisa/Development/chatter-ui/app/coffeescripts/quince/Controllers.coffee
```

Show at the command line?

**Comment by d2kagw** [comment]
Coffee outputs the script within moments without error.

**Comment by Sutto** [comment]
Is there any chance you'd be able to ping me on IRC (Sutto on freenode) about this - I'm not sure as to the cause and that'd help making debugging easier.

**Comment by Sutto** [comment]
How'd you end up going with this?

**Comment by Sutto** [comment]
Closing since I haven't heard back on it.
